//
//  NewsLoader.swift
//  wukela
//
//  Created by Paulo Custódio on 26/03/2020.
//  Copyright © 2020 Paulo Custódio. All rights reserved.
//

import UIKit
import CoreData

//load data from json and turn it into my data structure on Dictionary.swift
class NewsLoader {
    
    //store all the data that is retrieved from json file
    var news = [NewsData]()
    var filterNews = [NewsData]()
    var latestCount = 0
    
    var retrievedSource = ""
    var retrievedTopic = ""
    var newsBulk = [NewsData]()
    
    let categories = ["Sociedade",
                  "Desporto",
                  "Economia",
                  "Política",
                  "Cultura",
                  "Ciência e Tecnologia",
                  "Opinião"]
    
    let sources = ["Jornal Notícias",
                   "O País",
                   "Verdade",
                   "Jornal Angola",
                   "Novo Jornal"]
    
    var activeSources = ["","",""]
    var activeTopics = ["","",""]
    
    //run our load & sort functions when our class NewsLoader is created
    init() {
        self.load()
        sourceCheck()
        topicCheck()
        filter()

        //sort()
        //filtered()
    }
    
    //load our data
    func load() {
        //access file location of local json file
        //if file is accessed code inside is run
        if let fileLocation = URL(string : "http://paulocustodio.com/scraper/jornalnoticias_done.json") {
            //run do catch in case of an error
            do {
                //try to get data from json file
                let data = try Data(contentsOf: fileLocation)
                //decode our json
                let jsonDecoder = JSONDecoder()
                //get data from json file using decoder
                let dataFromJson = try jsonDecoder.decode([NewsData].self, from: data)
                newsBulk = dataFromJson
                print(data)
            } catch {
                print(error)
            }
        }
    }
    
    
    func sourceCheck() {
        
        //check Coredata for active news
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        let managedContext = appDelegate!.persistentContainer.viewContext
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "ActiveSources")
        do {
            let result = try managedContext.fetch(fetchRequest)

            //Loop over CoreData entities
            for data in result as! [NSManagedObject] {
                
                //get active sources from coredata
                retrievedSource = data.value(forKey: "isActiveSource") as! String
                
                //loop over active sources and add them to array
                for source in sources {
                    if retrievedSource == source {
                        activeTopics.insert(retrievedSource, at: 0)
                    }
                }
            }
        } catch {
            print("Failed")
        }
    }
    
    func topicCheck() {
        
        //check Coredata for active news
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        let managedContext = appDelegate!.persistentContainer.viewContext
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "ActiveTopics")
        do {
            let result = try managedContext.fetch(fetchRequest)

            //Loop over CoreData entities
            for data in result as! [NSManagedObject] {
                
                //loop over active topics
                retrievedTopic = data.value(forKey: "isActiveTopic") as! String
                
                for category in categories {
                    if retrievedTopic == category {
                        activeTopics.insert(retrievedTopic, at: 0)
                    }
                }

            
            }
            print("active topics are: \(activeTopics)")
        } catch {
            print("Failed")
        }
    }
    
    func filter() {
        //filter news source based on what is available on the array generated by coredata
        //when user toggles news source off, it triggers coredata, then updates this list
        let checkSourceOne = newsBulk.filter { $0.news_src == activeSources[0]}
        let checkSourceTwo = newsBulk.filter { $0.news_src == activeSources[1]}
        let checkSourceThree = newsBulk.filter { $0.news_src == activeSources[2]}
        
        //and then mash all the filtered news sources
        let newsSources = checkSourceThree + checkSourceTwo + checkSourceOne
        
        //check for active topics
        let checkTopicOne = newsBulk.filter { $0.cat == activeTopics[0]}
//        let checkTopicTwo = newsBulk.filter { $0.cat == activeTopics[1]}
//        let checkTopicThree = newsBulk.filter { $0.cat == activeTopics[2]}
//        let checkTopicFour = newsBulk.filter { $0.cat == activeTopics[3]}
//        let checkTopicFive = newsBulk.filter { $0.cat == activeTopics[4]}
//        let checkTopicSix = newsBulk.filter { $0.cat == activeTopics[5]}
//        let checkTopicSeven = newsBulk.filter { $0.cat == activeTopics[6]}
//        let checkTopicEight = newsBulk.filter { $0.cat == activeTopics[7]}
        
        let newsTopics = checkTopicOne
        print("these are les news with active topics: \(newsTopics)")
        news = newsSources + newsTopics

        
        //sort all news
        news = self.news.sorted { $0.epoch > $1.epoch }
        
        //filter recent news
        let currentTime = NSDate().timeIntervalSince1970
        let pastDay = currentTime - 86400
        filterNews = self.news.filter { $0.epoch > pastDay }
    }
    
    //sort our data
//    func sort() {
//        //sort by pt String field in ascending sequence (alphabetically) and ignore accents
//        self.news = self.news.sorted { $0.headline.localizedCaseInsensitiveCompare($1.headline) == ComparisonResult.orderedAscending }
//    }
//    
//    func filtered() {
//        //sort by pt String field in ascending sequence (alphabetically) and ignore accents
//        let currentTime = NSDate().timeIntervalSince1970
//        let pastHour = currentTime - 5000
//        print("today starts at \(pastHour)")
//        self.news = self.news.filter { $0.epoch > pastHour }
//    }

//    //sort our data
//    func sort() {
//        //sort by pt String field in ascending sequence (alphabetically) and ignore accents
//        self.news = self.news.sorted { $0.epoch > $1.epoch }
//    }
    
}

